package ncs.test3;

import java.util.Scanner;

public class ExceptionTest {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		Calculator cal = new Calculator();
		double sum = 0;
		
		try {
			System.out.print("2~5 사이의 정수를 입력하세요 : ");
			sum = cal.getSum(sc.nextInt());
			System.out.print("결과값 : " + sum);
		} catch (InvalidException e) {
			System.out.println(e.getMessage());
		}
		

	}

}
